# Generated by Django 4.0.3 on 2022-04-26 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 11, 3, 58, 641668, tzinfo=utc)),
        ),
    ]
