# Generated by Django 4.0.3 on 2022-04-26 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_us_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='created_at',
        ),
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 11, 8, 18, 269802, tzinfo=utc)),
        ),
    ]
