# Generated by Django 4.0.3 on 2022-04-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_contact_us_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productReview',
        ),
    ]
