# Generated by Django 4.0.3 on 2022-04-26 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0049_alter_userblog_created_at'),
        ('home', '0007_delete_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='productReview',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('review', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productreview')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronzaPanel.products')),
            ],
        ),
    ]
