# Generated by Django 3.2.13 on 2022-07-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0055_auto_20220723_2111'),
        ('home', '0008_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronzaPanel.amazonproduct'),
        ),
    ]
