# Generated by Django 4.1 on 2022-09-06 11:34

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_blog_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellYourDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('user_id', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('pPhone', models.EmailField(default='', max_length=100)),
                ('sPhone', models.EmailField(default='', max_length=100)),
                ('location', models.EmailField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('price', models.CharField(default='', max_length=100)),
                ('camera', models.CharField(default='', max_length=100)),
                ('flight_time', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('condition', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('label1', models.CharField(default='N/A', max_length=100, null=True)),
                ('label2', models.CharField(default='N/A', max_length=100, null=True)),
                ('label3', models.CharField(default='N/A', max_length=100, null=True)),
                ('label4', models.CharField(default='N/A', max_length=100, null=True)),
                ('input1', models.CharField(default='N/A', max_length=100, null=True)),
                ('input2', models.CharField(default='N/A', max_length=100, null=True)),
                ('input3', models.CharField(default='N/A', max_length=100, null=True)),
                ('input4', models.CharField(default='N/A', max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('thumbnail', models.FileField(default='', upload_to='sellYourDrone/thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='sellYourDroneImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to=home.models.sellYourDroneImages.upload_design_to)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sellyourdrone')),
            ],
        ),
    ]
