# Generated by Django 4.1 on 2022-09-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_place_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place_Order',
        ),
    ]
