# Generated by Django 4.1 on 2022-09-15 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_place_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=100)),
                ('user_id', models.CharField(default='', max_length=100)),
                ('p_price', models.CharField(default='', max_length=100)),
                ('p_quantity', models.CharField(default='', max_length=100)),
                ('p_total', models.CharField(default='', max_length=100)),
                ('p_grand_total', models.CharField(default='', max_length=100)),
                ('c_name', models.CharField(default='', max_length=100)),
                ('c_email', models.CharField(default='', max_length=100)),
                ('c_phone', models.CharField(default='', max_length=100)),
                ('c_city', models.CharField(default='', max_length=100)),
                ('c_zip', models.CharField(default='', max_length=100)),
                ('c_country', models.CharField(default='', max_length=100)),
                ('c_address1', models.CharField(default='', max_length=100)),
                ('c_address2', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('order_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
