# Generated by Django 4.0.3 on 2022-03-22 18:58

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTitlePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('feature1', models.TextField(default='')),
                ('feature2', models.TextField(default='')),
                ('feature3', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='about_title_post')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('Nature', 'Nature'), ('Urbanistic', 'Urbanistic'), ('Landscape', 'Landscape'), ('Sports', 'Sports'), ('Shooting', 'Shooting'), ('Traveling', 'Traveling')], default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('quote', models.CharField(default='', max_length=100)),
                ('quote_by', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=1000)),
                ('highlight_title', models.CharField(default='', max_length=100)),
                ('highlight1', models.CharField(default='', max_length=100)),
                ('highlight2', models.CharField(default='', max_length=100)),
                ('highlight3', models.CharField(default='', max_length=100)),
                ('highlight4', models.CharField(default='', max_length=100)),
                ('highlight5', models.CharField(default='', max_length=100)),
                ('highlight6', models.CharField(default='', max_length=100)),
                ('highlight_image', models.ImageField(default='', upload_to='services/highlights')),
                ('images', models.ImageField(default='', upload_to='services/detail')),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('socialmedia1', models.CharField(default='', max_length=100)),
                ('socialmedia2', models.CharField(default='', max_length=100)),
                ('socialmedia3', models.CharField(default='', max_length=100)),
                ('profile', models.ImageField(default='', upload_to='our_team')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Nature', 'Nature'), ('Urbanistic', 'Urbanistic'), ('Landscape', 'Landscape'), ('Sports', 'Sports'), ('Shooting', 'Shooting'), ('Traveling', 'Traveling')], default='', max_length=300)),
                ('price', models.CharField(default='', max_length=300)),
                ('feature1', models.CharField(default='', max_length=300)),
                ('feature2', models.CharField(default='', max_length=300)),
                ('feature3', models.CharField(default='', max_length=300)),
                ('feature4', models.CharField(default='', max_length=300)),
                ('feature5', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='QualityTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=1000)),
                ('icon', models.ImageField(default='', upload_to='about_quality_trust')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=1000)),
                ('icon', models.ImageField(default='', upload_to='services')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('skype', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('github', models.CharField(default='', max_length=100)),
                ('linkedin', models.CharField(default='', max_length=100)),
                ('google_plus', models.CharField(default='', max_length=100)),
                ('youtube', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('heading', models.CharField(default='', max_length=5000)),
                ('tags', models.CharField(default='', max_length=5000)),
                ('quote', models.CharField(default='', max_length=3000)),
                ('quote_by', models.CharField(default='', max_length=500)),
                ('description', ckeditor.fields.RichTextField(default='')),
                ('Icon', models.ImageField(default='', upload_to='Blog/Icons')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 22, 18, 58, 38, 340519, tzinfo=utc))),
            ],
        ),
    ]
