# Generated by Django 4.0.3 on 2022-03-23 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 12, 23, 55, 349964, tzinfo=utc)),
        ),
    ]
