# Generated by Django 4.0.3 on 2022-04-08 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0003_alter_userblog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainservices',
            name='highlight_image',
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 18, 38, 20, 241135, tzinfo=utc)),
        ),
    ]
