# Generated by Django 4.0.3 on 2022-04-09 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0004_remove_mainservices_highlight_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainservices',
            name='images',
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 7, 10, 54, 297093, tzinfo=utc)),
        ),
    ]
