# Generated by Django 4.0.3 on 2022-04-09 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0005_remove_mainservices_images_alter_userblog_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainServices',
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 7, 26, 41, 114217, tzinfo=utc)),
        ),
    ]
