# Generated by Django 4.0.3 on 2022-04-09 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0006_delete_mainservices_alter_userblog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourMainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('quote', models.CharField(default='', max_length=100)),
                ('quote_by', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=1000)),
                ('highlight_title', models.CharField(default='', max_length=100)),
                ('highlight1', models.CharField(default='', max_length=100)),
                ('highlight2', models.CharField(default='', max_length=100)),
                ('highlight3', models.CharField(default='', max_length=100)),
                ('highlight4', models.CharField(default='', max_length=100)),
                ('highlight5', models.CharField(default='', max_length=100)),
                ('highlight6', models.CharField(default='', max_length=100)),
                ('images', models.ImageField(default='', upload_to='services/detail')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 7, 28, 34, 777279, tzinfo=utc)),
        ),
    ]
