# Generated by Django 4.0.3 on 2022-04-09 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0007_ourmainservices_alter_userblog_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ourMainServices',
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 7, 43, 32, 915024, tzinfo=utc)),
        ),
    ]
