# Generated by Django 4.0.3 on 2022-04-09 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0008_delete_ourmainservices_alter_userblog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicestypes',
            old_name='icon',
            new_name='icons',
        ),
        migrations.AddField(
            model_name='servicestypes',
            name='highlight1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicestypes',
            name='highlight2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicestypes',
            name='highlight3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicestypes',
            name='highlight4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicestypes',
            name='highlight5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicestypes',
            name='highlight6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicestypes',
            name='quote',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicestypes',
            name='quote_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 7, 45, 38, 472791, tzinfo=utc)),
        ),
    ]
