# Generated by Django 4.0.3 on 2022-04-09 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0009_rename_icon_servicestypes_icons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 17, 20, 57, 897241, tzinfo=utc)),
        ),
    ]
