# Generated by Django 4.0.3 on 2022-04-09 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0011_rename_category_gallery_category1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='category1',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 17, 27, 8, 872596, tzinfo=utc)),
        ),
    ]
