# Generated by Django 4.0.3 on 2022-04-09 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0012_rename_category1_gallery_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 19, 23, 5, 183638, tzinfo=utc)),
        ),
    ]
