# Generated by Django 4.0.3 on 2022-04-11 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0013_ourteam_designation_alter_userblog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('header', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('price', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='Home_Main_Slider')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 16, 0, 3, 626474, tzinfo=utc)),
        ),
    ]
