# Generated by Django 4.0.3 on 2022-04-11 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0014_mainslider_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='backImage',
            field=models.ImageField(default='', upload_to='slide_back_Image'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 17, 21, 57, 549300, tzinfo=utc)),
        ),
    ]
