# Generated by Django 4.0.3 on 2022-04-12 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0015_mainslider_backimage_alter_userblog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='Home_HowITWORK')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 15, 48, 5, 145376, tzinfo=utc)),
        ),
    ]
