# Generated by Django 4.0.3 on 2022-04-12 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0016_homehiw_alter_userblog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('icon', models.ImageField(default='', upload_to='Home_HowToUse')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 16, 43, 4, 303435, tzinfo=utc)),
        ),
    ]
