# Generated by Django 4.0.3 on 2022-04-14 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0017_homehtu_alter_userblog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('feature1', models.CharField(default='', max_length=100)),
                ('feature2', models.CharField(default='', max_length=100)),
                ('feature3', models.CharField(default='', max_length=100)),
                ('icon', models.ImageField(default='', upload_to='Home_HowToUse')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 17, 16, 52, 967560, tzinfo=utc)),
        ),
    ]
