# Generated by Django 4.0.3 on 2022-04-14 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0018_homeabout_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeabout',
            name='icon',
            field=models.ImageField(default='', upload_to='Home_About'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 17, 18, 14, 839076, tzinfo=utc)),
        ),
    ]
