# Generated by Django 4.0.3 on 2022-04-15 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0019_alter_homeabout_icon_alter_userblog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('cPrice', models.CharField(default='', max_length=100)),
                ('dPrice', models.CharField(default='', max_length=100)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('length', models.CharField(default='', max_length=100)),
                ('fabric', models.CharField(default='', max_length=100)),
                ('warranty', models.CharField(default='', max_length=100)),
                ('sku', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('Metal, Drone', 'Metal, Drone')], default='', max_length=100)),
                ('range', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('icon', models.ImageField(default='', upload_to='Home_About')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 10, 45, 20, 968670, tzinfo=utc)),
        ),
    ]
