# Generated by Django 4.0.3 on 2022-04-15 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0020_products_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('RED', 'RED'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 11, 4, 8, 974431, tzinfo=utc)),
        ),
    ]
