# Generated by Django 4.0.3 on 2022-04-15 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0022_alter_products_size_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fabric',
            field=models.CharField(choices=[('Cotton', 'Small'), ('Silk', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='warranty',
            field=models.CharField(choices=[('6 Month', '6 Month'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('5 Year', '5 Year')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 11, 25, 12, 165972, tzinfo=utc)),
        ),
    ]
