# Generated by Django 4.0.3 on 2022-04-16 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0023_alter_products_fabric_alter_products_warranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 7, 5, 1, 827603, tzinfo=utc)),
        ),
    ]
