# Generated by Django 4.0.3 on 2022-04-16 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0026_alter_products_warranty_alter_userblog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSRFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied_clients', models.CharField(default='', max_length=100)),
                ('resolution', models.CharField(default='', max_length=1000)),
                ('flight_time', models.CharField(default='', max_length=1000)),
                ('project_done', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='qualitytrust',
            name='Description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='servicestypes',
            name='Description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 15, 28, 37, 799394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
