# Generated by Django 4.0.3 on 2022-04-16 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0027_homesrfp_alter_gallery_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(default='', max_length=200)),
                ('icon', models.ImageField(default='', upload_to='Home/Video_Gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 17, 6, 31, 117750, tzinfo=utc)),
        ),
    ]
