# Generated by Django 4.0.3 on 2022-04-17 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0028_videogallery_alter_userblog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatPeopleSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=200)),
                ('say_something', models.CharField(default='', max_length=200)),
                ('icon', models.ImageField(default='', upload_to='Home/Testimonials')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 15, 34, 12, 14006, tzinfo=utc)),
        ),
    ]
