# Generated by Django 4.0.3 on 2022-04-17 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0029_whatpeoplesay_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 15, 37, 13, 641076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='whatpeoplesay',
            name='say_something',
            field=models.TextField(default='', max_length=200),
        ),
    ]
