# Generated by Django 4.0.3 on 2022-04-17 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0030_alter_userblog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='qualitytrust',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='servicestypes',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 16, 4, 58, 791171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='whatpeoplesay',
            name='say_something',
            field=models.TextField(default=''),
        ),
    ]
