# Generated by Django 4.0.3 on 2022-04-17 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0031_alter_gallery_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('logo', models.ImageField(default='', upload_to='Home/Partners')),
            ],
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 16, 27, 10, 497690, tzinfo=utc)),
        ),
    ]
