# Generated by Django 4.0.3 on 2022-04-18 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0033_socialmedia_facebook_socialmedia_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='', upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 11, 14, 34, 62755, tzinfo=utc)),
        ),
    ]
