# Generated by Django 4.0.3 on 2022-04-19 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0035_products_flight_time_products_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Fabric', 'Fabric')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 44, 31, 156395, tzinfo=utc)),
        ),
    ]
