# Generated by Django 4.0.3 on 2022-04-19 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0036_alter_products_category_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.CharField(choices=[('Featured', 'Featured'), ('Not_Featured', 'Not_Featured')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 47, 48, 712488, tzinfo=utc)),
        ),
    ]
