# Generated by Django 4.0.3 on 2022-04-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0037_products_featured_alter_userblog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblog',
            name='Icon',
        ),
        migrations.RemoveField(
            model_name='userblog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userblog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userblog',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='userblog',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='userblog',
            name='quote_by',
        ),
        migrations.RemoveField(
            model_name='userblog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userblog',
            name='title',
        ),
    ]
