# Generated by Django 4.0.3 on 2022-04-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0038_remove_userblog_icon_remove_userblog_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userBlog',
        ),
    ]
