# Generated by Django 4.0.3 on 2022-04-19 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0039_delete_userblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBlog',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('heading', models.CharField(default='', max_length=5000)),
                ('tags', models.CharField(default='', max_length=5000)),
                ('quote', models.CharField(default='', max_length=3000)),
                ('quote_by', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('Icon', models.ImageField(default='', upload_to='Blog/Icons')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 16, 48, 50, 32043, tzinfo=utc))),
            ],
        ),
    ]
