# Generated by Django 4.0.3 on 2022-04-21 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0040_userblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 10, 46, 26, 523886, tzinfo=utc)),
        ),
    ]
