# Generated by Django 4.0.3 on 2022-04-21 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0041_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 11, 48, 52, 937797, tzinfo=utc)),
        ),
    ]
