# Generated by Django 3.2.13 on 2022-06-19 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0049_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 18, 53, 32, 630921, tzinfo=utc)),
        ),
    ]
