# Generated by Django 3.2.13 on 2022-06-27 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0050_alter_userblog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='icon',
        ),
        migrations.AddField(
            model_name='products',
            name='Images',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 19, 40, 11, 464946, tzinfo=utc)),
        ),
    ]
