# Generated by Django 3.2.13 on 2022-06-29 04:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import dronzaPanel.models


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0051_auto_20220627_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Images',
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 4, 44, 0, 208838, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='productImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to=dronzaPanel.models.productImages.upload_design_to)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronzaPanel.products')),
            ],
        ),
    ]
