# Generated by Django 3.2.13 on 2022-07-03 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0052_auto_20220629_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mainIcon',
            field=models.FileField(default='', upload_to='DronzaProducts/MainIcon'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 12, 46, 15, 311381, tzinfo=utc)),
        ),
    ]
