# Generated by Django 3.2.13 on 2022-07-23 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0054_auto_20220723_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Fabric', 'Fabric')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='featured',
            field=models.CharField(choices=[('Featured', 'Featured'), ('Not_Featured', 'Not_Featured')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 21, 11, 57, 609772, tzinfo=utc)),
        ),
    ]
