# Generated by Django 3.2.13 on 2022-07-30 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0055_auto_20220723_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestypes',
            name='type',
            field=models.CharField(choices=[('RegularService', 'RegularService'), ('MainService', 'MainService')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 21, 41, 34, 813557, tzinfo=utc)),
        ),
    ]
