# Generated by Django 3.2.13 on 2022-08-04 06:34

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0056_auto_20220730_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 34, 26, 702216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
