# Generated by Django 3.2.13 on 2022-08-04 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0057_auto_20220804_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 9, 13, 22, 444713, tzinfo=utc)),
        ),
    ]
