# Generated by Django 3.2.13 on 2022-08-05 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0058_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttitlepost',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Wireless', 'Wireless')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homehiw',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homehtu',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homesrfp',
            name='flight_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homesrfp',
            name='project_done',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homesrfp',
            name='resolution',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Urbanistic', 'Urbanistic'), ('Landscape', 'Landscape'), ('Sports', 'Sports'), ('Shooting', 'Shooting'), ('Traveling', 'Traveling')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='feature1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='feature2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='feature3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='feature4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='feature5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Wireless', 'Wireless')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='qualitytrust',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='github',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='google_plus',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='linkedin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='skype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='youtube',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 3, 52, 17, 822454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='heading',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='quote',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='quote_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
