# Generated by Django 3.2.13 on 2022-08-05 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0059_auto_20220805_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Wireless', 'Wireless'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Wireless', 'Wireless'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 4, 15, 29, 784966, tzinfo=utc)),
        ),
    ]
