# Generated by Django 4.1 on 2022-09-06 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0062_auto_20220807_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 11, 34, 2, 807492, tzinfo=datetime.timezone.utc)),
        ),
    ]
