# Generated by Django 4.1 on 2022-09-11 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0063_alter_userblog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='mainIcon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='dPrice',
            new_name='input1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='fabric',
            new_name='input2',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='length',
            new_name='input3',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='range',
            new_name='input4',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='size',
            new_name='input5',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='sku',
            new_name='input6',
        ),
        migrations.RemoveField(
            model_name='products',
            name='title',
        ),
        migrations.RemoveField(
            model_name='products',
            name='warranty',
        ),
        migrations.AddField(
            model_name='products',
            name='label1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='label2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='label3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='label4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='label5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='label6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 20, 7, 40, 771079, tzinfo=datetime.timezone.utc)),
        ),
    ]
