# Generated by Django 4.1 on 2022-09-15 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0064_rename_mainicon_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 5, 42, 19, 747250, tzinfo=datetime.timezone.utc)),
        ),
    ]
