# Generated by Django 4.1 on 2022-09-15 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronzaPanel', '0066_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 14, 37, 0, 812245, tzinfo=datetime.timezone.utc)),
        ),
    ]
