from .about import *
from .sliders import *
from .how_it_work import *
from .how_to_use import *
from .about_title_post import *
from .products import *
from .amazon_products import *
from .drone_parts import *
from .quality_trust import *
from .satisfied_clients import *
from .video_gallery import *
from .what_people_say import *
from .our_partner import *
from .our_team import *
from .services import *
from .pricing import *
from .gallery import *
from .social_media import *
from .blog import *
from .seo_tags import *
from .email_content import *

