from .accounts import *
from .panel_home import *
from .communication import *
from .products import *
from .client_people_partner import *
from .social_media import *
from .services_gallery_pricing import *
from .delete_record import *
from .update_record import *
from .blog import *
