class DJANGO_VIEWS:
    USER_REGISTER = 'home/views/accounts/user_registration'
    USER_LOGIN = 'home/views/accounts/user_login'
    HOME_PAGE = 'home/views/home_page/index'
    BLOG = 'home/views/blog/blog'
    SEARCH_BLOG = 'home/views/blog/search_blog'
    READ_BLOG = 'home/views/blog/read_blog_post'
    CUSTOMER_PRODUCT = 'home/views/customer_product/customer_product'
    GALLERY = 'home/views/gallery/gallery'
    SERVICES = 'home/views/services/services'
    PRIVACY_POLICY = 'home/views/privacy_policy/privacy_policy'
    BLOG_REVIEWS = 'home/views/blog_post_review/blog_post_review'
    SELL_DRONES = 'home/views/sell_your_drone/sellDrones'
    SELL_DRONES_SEARCH = 'home/views/sell_your_drone/search_by_location_category'
    NEWS_LETTER = 'home/views/news_letter/news_letter_subscriber'
    RECORD_DETAILS = 'home/views/record_detail/get_instance_detail'
    UPDATE_RECORD = 'home/views/update_record/update_record_by_uuid'
    DELETE_RECORD = 'home/views/delete_record/delete_record_by_uuid'
